module.exports = [
    {
        title: "course",
        imgurl: "https://wallpapercave.com/wp/wp6782679.jpg",
        description: "Lorem ipsum dolor sit amet mollis felis dapibus arcur donec viverra  to phasellus eget. Etiam maecenas vel vici quis dictum rutrum nec nisi et.Ac penatibus aenean laoreet.",
        date: 1,
        month: "Feb",
        writtenby: "Admin",
    },
    {
        title: "course",
        imgurl: "https://wallpapercave.com/wp/wp6782679.jpg",
        description: "Lorem ipsum dolor sit amet mollis felis dapibus arcur donec viverra  to phasellus eget. Etiam maecenas vel vici quis dictum rutrum nec nisi et.Ac penatibus aenean laoreet.",
        date: 1,
        month: "Feb",
        writtenby: "Admin",
    },
    {
        title: "course",
        imgurl: "https://wallpapercave.com/wp/wp6782679.jpg",
        description: "Lorem ipsum dolor sit amet mollis felis dapibus arcur donec viverra  to phasellus eget. Etiam maecenas vel vici quis dictum rutrum nec nisi et.Ac penatibus aenean laoreet.",
        date: 1,
        month: "Feb",
        writtenby: "Admin",
    },
    {
        title: "course",
        imgurl: "https://wallpapercave.com/wp/wp6782679.jpg",
        description: "Lorem ipsum dolor sit amet mollis felis dapibus arcur donec viverra  to phasellus eget. Etiam maecenas vel vici quis dictum rutrum nec nisi et.Ac penatibus aenean laoreet.",
        date: 1,
        month: "Feb",
        writtenby: "Admin",
    },
    {
        title: "course",
        imgurl: "https://wallpapercave.com/wp/wp6782679.jpg",
        description: "Lorem ipsum dolor sit amet mollis felis dapibus arcur donec viverra  to phasellus eget. Etiam maecenas vel vici quis dictum rutrum nec nisi et.Ac penatibus aenean laoreet.",
        date: 1,
        month: "Feb",
        writtenby: "Admin",
    },
];
